"""Fleet-level analytics endpoints backed by OTEL telemetry data."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import structlog
from dishka.integrations.fastapi import DishkaRoute, FromDishka
from fastapi import APIRouter, Query
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(route_class=DishkaRoute, tags=["analytics"])
log = structlog.get_logger()

# ---------------------------------------------------------------------------
# Model pricing — loaded once from the bundled JSON generated by
# tools/update_model_pricing.py (sourced from LiteLLM community data).
# ---------------------------------------------------------------------------

_PRICING_PATH = Path(__file__).resolve().parent.parent / "data" / "model_pricing.json"
_MODEL_PRICING: dict[str, dict] = {}

try:
    _MODEL_PRICING = json.loads(_PRICING_PATH.read_text())
    log.info("model_pricing_loaded", count=len(_MODEL_PRICING))
except FileNotFoundError:
    log.warning("model_pricing_file_missing", path=str(_PRICING_PATH))
except Exception:
    log.exception("model_pricing_load_error")


def _normalize_model_key(model: str) -> str:
    """Lowercase, collapse non-alnum to hyphens — matches LiteLLM keys."""
    import re
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]", "-", model.lower())).strip("-")


@router.get("/analytics/overview")
async def analytics_overview(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> dict[str, object]:
    """Aggregate analytics over the given period (days)."""
    from backend.persistence.telemetry_summary_repo import TelemetrySummaryRepo

    repo = TelemetrySummaryRepo(session)
    agg = await repo.aggregate(period_days=period)
    cost_trend = await repo.cost_by_day(period_days=period)

    total_input = agg.get("total_input_tokens", 0) or 0
    total_cache = agg.get("total_cache_read", 0) or 0
    cache_rate = (total_cache / total_input * 100) if total_input else 0

    total_tools = agg.get("total_tool_calls", 0) or 0
    total_failures = agg.get("total_tool_failures", 0) or 0
    tool_success_rate = ((total_tools - total_failures) / total_tools * 100) if total_tools else 100

    return {
        "period": period,
        "totalJobs": agg.get("total_jobs", 0),
        "succeeded": agg.get("succeeded", 0),
        "failed": agg.get("failed", 0),
        "cancelled": agg.get("cancelled", 0),
        "running": agg.get("running", 0),
        "totalCostUsd": float(agg.get("total_cost_usd", 0) or 0),
        "totalTokens": agg.get("total_tokens", 0),
        "avgDurationMs": float(agg.get("avg_duration_ms", 0) or 0),
        "totalPremiumRequests": float(agg.get("total_premium_requests", 0) or 0),
        "totalToolCalls": total_tools,
        "totalToolFailures": total_failures,
        "toolSuccessRate": round(tool_success_rate, 1),
        "cacheHitRate": round(cache_rate, 1),
        "costTrend": cost_trend,
    }


@router.get("/analytics/models")
async def analytics_models(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> dict[str, object]:
    """Per-model cost and usage breakdown."""
    from backend.persistence.telemetry_summary_repo import TelemetrySummaryRepo

    rows = await TelemetrySummaryRepo(session).cost_by_model(period_days=period)
    return {"period": period, "models": rows}


@router.get("/analytics/tools")
async def analytics_tools(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> dict[str, object]:
    """Tool performance stats (call counts, failure rates, latency)."""
    from backend.persistence.telemetry_spans_repo import TelemetrySpansRepo

    stats = await TelemetrySpansRepo(session).tool_stats(period_days=period)
    return {"period": period, "tools": stats}


@router.get("/analytics/repos")
async def analytics_repos(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
) -> dict[str, object]:
    """Per-repo cost and usage breakdown."""
    from backend.persistence.telemetry_summary_repo import TelemetrySummaryRepo

    rows = await TelemetrySummaryRepo(session).cost_by_repo(period_days=period)
    return {"period": period, "repos": rows}


@router.get("/analytics/jobs")
async def analytics_jobs(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 7,
    sdk: str | None = None,
    model: str | None = None,
    status: str | None = None,
    repo: str | None = None,
    sort: str = "completed_at",
    desc: bool = True,
    limit: Annotated[int, Query(ge=1, le=500)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> dict[str, object]:
    """Paginated per-job telemetry table."""
    from backend.persistence.telemetry_summary_repo import TelemetrySummaryRepo

    rows = await TelemetrySummaryRepo(session).query(
        period_days=period,
        sdk=sdk,
        model=model,
        status=status,
        repo=repo,
        sort=sort,
        desc=desc,
        limit=limit,
        offset=offset,
    )
    return {"period": period, "jobs": rows}


@router.get("/analytics/pricing")
async def analytics_pricing(
    models: str = Query(
        ...,
        description="Comma-separated model names to look up (e.g. 'claude-sonnet-4-6,claude-opus-4-5')",
    ),
) -> dict[str, dict | None]:
    """Return pricing info for the requested models.

    Looks up each model by exact key first, then falls back to normalised
    matching.  Returns ``null`` for models not found in the pricing data.
    """
    result: dict[str, dict | None] = {}
    for raw in models.split(","):
        name = raw.strip()
        if not name:
            continue
        # Exact match first, then normalised
        entry = _MODEL_PRICING.get(name)
        if entry is None:
            norm = _normalize_model_key(name)
            entry = _MODEL_PRICING.get(norm)
        result[name] = entry
    return result


# ---------------------------------------------------------------------------
# Cost Analytics Endpoints
# ---------------------------------------------------------------------------


@router.get("/analytics/cost-drivers/{job_id}")
async def cost_drivers_for_job(
    job_id: str,
    session: FromDishka[AsyncSession],
) -> dict[str, object]:
    """Per-job cost attribution breakdown by dimension."""
    from backend.persistence.cost_attribution_repo import CostAttributionRepo

    rows = await CostAttributionRepo(session).for_job(job_id)
    by_dimension: dict[str, list[dict]] = {}
    for row in rows:
        dim = row.get("dimension", "unknown")
        by_dimension.setdefault(dim, []).append(row)
    return {"jobId": job_id, "dimensions": by_dimension}


@router.get("/analytics/cost-drivers")
async def fleet_cost_drivers(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
    dimension: str | None = None,
) -> dict[str, object]:
    """Fleet-wide cost attribution: top cost buckets across all dimensions."""
    from backend.persistence.cost_attribution_repo import CostAttributionRepo

    repo = CostAttributionRepo(session)
    if dimension:
        rows = await repo.by_dimension(dimension, period_days=period)
        return {"period": period, "dimension": dimension, "buckets": rows}
    summary = await repo.fleet_summary(period_days=period)
    return {"period": period, "summary": summary}


@router.get("/analytics/file-access/{job_id}")
async def file_access_for_job(
    job_id: str,
    session: FromDishka[AsyncSession],
) -> dict[str, object]:
    """File access stats for a job — rereads, most-accessed files."""
    from backend.persistence.file_access_repo import FileAccessRepo

    repo = FileAccessRepo(session)
    stats = await repo.reread_stats(job_id)
    top_files = await repo.most_accessed_files(job_id=job_id)
    return {"jobId": job_id, "stats": stats, "topFiles": top_files}


@router.get("/analytics/file-access")
async def fleet_file_access(
    session: FromDishka[AsyncSession],
    period: Annotated[int, Query(ge=1, le=365)] = 30,
) -> dict[str, object]:
    """Fleet-wide most-accessed files across all jobs."""
    from backend.persistence.file_access_repo import FileAccessRepo

    top_files = await FileAccessRepo(session).most_accessed_files(period_days=period)
    return {"period": period, "topFiles": top_files}


@router.get("/analytics/turn-economics/{job_id}")
async def turn_economics_for_job(
    job_id: str,
    session: FromDishka[AsyncSession],
) -> dict[str, object]:
    """Per-turn cost curve for a specific job."""
    from backend.persistence.cost_attribution_repo import CostAttributionRepo
    from backend.persistence.telemetry_summary_repo import TelemetrySummaryRepo

    summary = await TelemetrySummaryRepo(session).get(job_id)
    turns = await CostAttributionRepo(session).for_job(job_id)
    turn_data = [r for r in turns if r.get("dimension") == "turn"]
    return {
        "jobId": job_id,
        "totalTurns": summary.get("total_turns", 0) if summary else 0,
        "peakTurnCostUsd": summary.get("peak_turn_cost_usd", 0) if summary else 0,
        "avgTurnCostUsd": summary.get("avg_turn_cost_usd", 0) if summary else 0,
        "costFirstHalfUsd": summary.get("cost_first_half_usd", 0) if summary else 0,
        "costSecondHalfUsd": summary.get("cost_second_half_usd", 0) if summary else 0,
        "turnCurve": turn_data,
    }


# ---------------------------------------------------------------------------
# Statistical Observations
# ---------------------------------------------------------------------------


@router.get("/analytics/observations")
async def list_observations(
    session: FromDishka[AsyncSession],
    category: str | None = None,
    severity: str | None = None,
) -> dict[str, object]:
    """List active cost observations / anomalies."""
    from backend.persistence.observations_repo import ObservationsRepo

    rows = await ObservationsRepo(session).list_active(
        category=category, severity=severity
    )
    return {"observations": rows}


@router.post("/analytics/observations/{observation_id}/dismiss")
async def dismiss_observation(
    observation_id: int,
    session: FromDishka[AsyncSession],
) -> dict[str, str]:
    """Dismiss an observation."""
    from backend.persistence.observations_repo import ObservationsRepo

    await ObservationsRepo(session).dismiss(observation_id)
    await session.commit()
    return {"status": "dismissed"}


@router.post("/analytics/analyse")
async def trigger_analysis(
    session: FromDishka[AsyncSession],
) -> dict[str, object]:
    """Manually trigger the statistical analysis pass."""
    from backend.services.statistical_analysis import run_analysis

    count = await run_analysis(session)
    await session.commit()
    return {"observations_written": count}
