"""Tests for configuration loading and initialization."""

from __future__ import annotations

from typing import TYPE_CHECKING

from backend.config import CPLConfig, init_config, load_config

if TYPE_CHECKING:
    from pathlib import Path


def test_load_config_returns_defaults_when_missing(tmp_path: Path) -> None:
    config = load_config(tmp_path / "nonexistent.yaml")
    assert isinstance(config, CPLConfig)
    assert config.server.host == "127.0.0.1"
    assert config.server.port == 8080
    assert config.runtime.max_concurrent_jobs == 2
    assert config.repos == []


def test_load_config_parses_yaml(tmp_path: Path) -> None:
    cfg_file = tmp_path / "config.yaml"
    cfg_file.write_text(
        """\
server:
  host: 0.0.0.0
  port: 9090

runtime:
  max_concurrent_jobs: 4

repos:
  - /repos/a
  - /repos/b
"""
    )
    config = load_config(cfg_file)
    assert config.server.host == "0.0.0.0"
    assert config.server.port == 9090
    assert config.runtime.max_concurrent_jobs == 4
    assert config.repos == ["/repos/a", "/repos/b"]


def test_load_config_ignores_unknown_keys(tmp_path: Path) -> None:
    cfg_file = tmp_path / "config.yaml"
    cfg_file.write_text(
        """\
server:
  host: 127.0.0.1
  unknown_key: value

future_section:
  something: true
"""
    )
    config = load_config(cfg_file)
    assert config.server.host == "127.0.0.1"


def test_init_config_creates_file(tmp_path: Path) -> None:
    cfg_path = tmp_path / "sub" / "config.yaml"
    result = init_config(cfg_path)
    assert result == cfg_path
    assert cfg_path.exists()
    content = cfg_path.read_text()
    assert "server:" in content
    assert "host: 127.0.0.1" in content


def test_init_config_roundtrips(tmp_path: Path) -> None:
    """Config generated by init can be loaded back."""
    cfg_path = tmp_path / "config.yaml"
    init_config(cfg_path)
    config = load_config(cfg_path)
    assert config.server.port == 8080
    assert config.runtime.worktrees_dirname == ".cpl-worktrees"
    assert config.retention.artifact_retention_days == 30
