/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return service health and status.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs with optional state filter and cursor pagination.
         *
         *     Pass archived=true to list only archived jobs, archived=false to
         *     exclude them. Default (None) returns all jobs.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new job.
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Get full job detail.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a running or queued job.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Job
         * @description Create a new job from an existing job's configuration.
         */
        post: operations["rerun_job_api_jobs__job_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Job
         * @description Send a silent pause instruction to the agent of a running job.
         */
        post: operations["pause_job_api_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue Job
         * @description Create a follow-up job with a new instruction on the same repo/config.
         */
        post: operations["continue_job_api_jobs__job_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Job
         * @description Resume a completed/failed/canceled job in-place with a new instruction.
         */
        post: operations["resume_job_api_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return the model list cached at server startup.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Logs
         * @description Return historical log lines for a job, filtered by minimum severity.
         *
         *     ``level`` is a *minimum* severity filter (inclusive):
         *     - ``debug``  → all lines (debug, info, warn, error)
         *     - ``info``   → info, warn, error
         *     - ``warn``   → warn, error
         *     - ``error``  → error only
         */
        get: operations["get_job_logs_api_jobs__job_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Diff
         * @description Return the current diff for a job.
         *
         *     For running jobs, calculates a fresh diff from the worktree.
         *     For completed/archived jobs, returns the last stored diff snapshot.
         */
        get: operations["get_job_diff_api_jobs__job_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Transcript
         * @description Return historical transcript entries for a job from the event store.
         */
        get: operations["get_job_transcript_api_jobs__job_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Timeline
         * @description Return historical progress_headline milestones for a job.
         *
         *     Events with ``replaces_count > 0`` retroactively collapse earlier entries,
         *     so the returned list is the final milestone timeline, not raw events.
         */
        get: operations["get_job_timeline_api_jobs__job_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Telemetry
         * @description Get telemetry data for a job run.
         */
        get: operations["get_job_telemetry_api_jobs__job_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Job
         * @description Resolve a succeeded job: merge, create PR, discard, or resolve with agent.
         */
        post: operations["resolve_job_api_jobs__job_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Job
         * @description Archive a completed job (hide from Kanban board).
         */
        post: operations["archive_job_api_jobs__job_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive Job
         * @description Unarchive a job (show on Kanban board again).
         */
        post: operations["unarchive_job_api_jobs__job_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE stream for live events.
         *
         *     Optional ``job_id`` query param scopes the stream to a single job.
         *     ``Last-Event-ID`` (header or query) enables reconnection replay.
         */
        get: operations["stream_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description List all approvals for a job.
         */
        get: operations["list_approvals_api_jobs__job_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Approval
         * @description Approve or reject a pending approval request.
         */
        post: operations["resolve_approval_api_approvals__approval_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/approvals/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trust Job
         * @description Trust a job session — auto-approve all current and future permission requests.
         */
        post: operations["trust_job_api_jobs__job_id__approvals_trust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Inject an operator message into a running job's agent session.
         */
        post: operations["send_message_api_jobs__job_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description List all artifacts for a job.
         */
        get: operations["list_artifacts_api_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact
         * @description Download an artifact file.
         */
        get: operations["download_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspace
         * @description List files in the job's worktree (max 200 entries per page).
         */
        get: operations["list_workspace_api_jobs__job_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/workspace/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace File
         * @description Get the contents of a single file in the job's worktree.
         */
        get: operations["get_workspace_file_api_jobs__job_id__workspace_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe
         * @description Upload audio, receive transcript.
         */
        post: operations["transcribe_api_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get current settings as structured data.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Update settings. Only provided fields are changed.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repos
         * @description List registered repository paths.
         */
        get: operations["list_repos_api_settings_repos_get"];
        put?: never;
        /**
         * Register Repo Endpoint
         * @description Register a repository (local path or remote URL).
         */
        post: operations["register_repo_endpoint_api_settings_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/repos/{repo_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repo Detail
         * @description Get detailed config for a single registered repository.
         */
        get: operations["get_repo_detail_api_settings_repos__repo_path__get"];
        put?: never;
        post?: never;
        /**
         * Unregister Repo Endpoint
         * @description Remove a repository from the allowlist.
         */
        delete: operations["unregister_repo_endpoint_api_settings_repos__repo_path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/cleanup-worktrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Worktrees
         * @description Clean up completed job worktrees for all registered repos.
         */
        post: operations["cleanup_worktrees_api_settings_cleanup_worktrees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse Directories
         * @description List directories at a given path for the repo browser.
         *
         *     Returns subdirectories and indicates which are git repos.
         */
        get: operations["browse_directories_api_settings_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Status
         * @description Check auth status for all detected git hosting platforms.
         */
        get: operations["get_platform_status_api_platforms_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sdks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sdks
         * @description List available agent SDKs and their status.
         */
        get: operations["list_sdks_api_sdks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all active terminal sessions.
         */
        get: operations["list_sessions_api_terminal_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new terminal session.
         */
        post: operations["create_session_api_terminal_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Kill a terminal session.
         */
        delete: operations["delete_session_api_terminal_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Ai
         * @description Translate natural language to a shell command using the utility model.
         */
        post: operations["ask_ai_api_terminal_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalResolution
         * @enum {string}
         */
        ApprovalResolution: "approved" | "rejected";
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Id */
            id: string;
            /** Jobid */
            jobId: string;
            /** Description */
            description: string;
            /** Proposedaction */
            proposedAction: string | null;
            /**
             * Requestedat
             * Format: date-time
             */
            requestedAt: string;
            /** Resolvedat */
            resolvedAt: string | null;
            resolution: components["schemas"]["ApprovalResolution"] | null;
            /** Requiresexplicitapproval */
            requiresExplicitApproval: boolean;
        };
        /** ArtifactListResponse */
        ArtifactListResponse: {
            /** Items */
            items: components["schemas"]["ArtifactResponse"][];
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Id */
            id: string;
            /** Jobid */
            jobId: string;
            /** Name */
            name: string;
            type: components["schemas"]["ArtifactType"];
            /** Mimetype */
            mimeType: string;
            /** Sizebytes */
            sizeBytes: number;
            phase: components["schemas"]["ExecutionPhase"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "diff_snapshot" | "agent_summary" | "session_snapshot" | "session_log" | "document" | "custom";
        /** AskRequest */
        AskRequest: {
            /** Prompt */
            prompt: string;
            /** Context */
            context?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Command */
            command: string;
            /** Explanation */
            explanation: string;
        };
        /** Body_transcribe_api_voice_transcribe_post */
        Body_transcribe_api_voice_transcribe_post: {
            /** Audio */
            audio: string;
        };
        /** ContinueJobRequest */
        ContinueJobRequest: {
            /** Instruction */
            instruction: string;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /** Repo */
            repo: string;
            /** Prompt */
            prompt: string;
            /** Base Ref */
            base_ref?: string | null;
            /** Branch */
            branch?: string | null;
            permission_mode?: components["schemas"]["PermissionMode"] | null;
            /** Model */
            model?: string | null;
            /** Sdk */
            sdk?: string | null;
            /** Verify */
            verify?: boolean | null;
            /** Self Review */
            self_review?: boolean | null;
            /** Max Turns */
            max_turns?: number | null;
            /** Verify Prompt */
            verify_prompt?: string | null;
            /** Self Review Prompt */
            self_review_prompt?: string | null;
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            /** Id */
            id: string;
            /** State */
            state: string;
            /** Title */
            title?: string | null;
            /** Branch */
            branch?: string | null;
            /** Worktreepath */
            worktreePath?: string | null;
            /**
             * Sdk
             * @default copilot
             */
            sdk: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Shell */
            shell?: string | null;
            /** Cwd */
            cwd?: string | null;
            /** Jobid */
            jobId?: string | null;
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Id */
            id: string;
            /** Shell */
            shell: string;
            /** Cwd */
            cwd: string;
            /** Jobid */
            jobId?: string | null;
            /** Pid */
            pid: number;
        };
        /** DiffFileModel */
        DiffFileModel: {
            /** Path */
            path: string;
            status: components["schemas"]["DiffFileStatus"];
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Hunks */
            hunks: components["schemas"]["DiffHunkModel"][];
        };
        /**
         * DiffFileStatus
         * @enum {string}
         */
        DiffFileStatus: "added" | "modified" | "deleted" | "renamed";
        /** DiffHunkModel */
        DiffHunkModel: {
            /** Oldstart */
            oldStart: number;
            /** Oldlines */
            oldLines: number;
            /** Newstart */
            newStart: number;
            /** Newlines */
            newLines: number;
            /** Lines */
            lines: components["schemas"]["DiffLineModel"][];
        };
        /** DiffLineModel */
        DiffLineModel: {
            type: components["schemas"]["DiffLineType"];
            /** Content */
            content: string;
        };
        /**
         * DiffLineType
         * @enum {string}
         */
        DiffLineType: "context" | "addition" | "deletion";
        /**
         * ExecutionPhase
         * @enum {string}
         */
        ExecutionPhase: "environment_setup" | "agent_reasoning" | "verification" | "finalization" | "post_completion";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
            /** Uptimeseconds */
            uptimeSeconds: number;
            /** Activejobs */
            activeJobs: number;
            /** Queuedjobs */
            queuedJobs: number;
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "healthy";
        /** JobListResponse */
        JobListResponse: {
            /** Items */
            items: components["schemas"]["JobResponse"][];
            /** Cursor */
            cursor: string | null;
            /** Hasmore */
            hasMore: boolean;
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: string;
            /** Repo */
            repo: string;
            /** Prompt */
            prompt: string;
            /** Title */
            title?: string | null;
            /** State */
            state: string;
            /** Baseref */
            baseRef: string;
            /** Worktreepath */
            worktreePath: string | null;
            /** Branch */
            branch: string | null;
            permissionMode?: components["schemas"]["PermissionMode"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Completedat */
            completedAt: string | null;
            /** Prurl */
            prUrl?: string | null;
            /** Mergestatus */
            mergeStatus?: string | null;
            /** Resolution */
            resolution?: string | null;
            /** Archivedat */
            archivedAt?: string | null;
            /** Failurereason */
            failureReason?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Sdk
             * @default copilot
             */
            sdk: string;
            /** Worktreename */
            worktreeName?: string | null;
            /** Verify */
            verify?: boolean | null;
            /** Selfreview */
            selfReview?: boolean | null;
            /** Maxturns */
            maxTurns?: number | null;
            /** Verifyprompt */
            verifyPrompt?: string | null;
            /** Selfreviewprompt */
            selfReviewPrompt?: string | null;
        };
        /**
         * LogLevel
         * @enum {string}
         */
        LogLevel: "debug" | "info" | "warn" | "error";
        /** LogLinePayload */
        LogLinePayload: {
            /** Jobid */
            jobId: string;
            /** Seq */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            level: components["schemas"]["LogLevel"];
            /** Message */
            message: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PermissionMode
         * @enum {string}
         */
        PermissionMode: "auto" | "read_only" | "approval_required";
        /** PlatformStatusListResponse */
        PlatformStatusListResponse: {
            /** Items */
            items: components["schemas"]["PlatformStatusResponse"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PlatformStatusResponse */
        PlatformStatusResponse: {
            /** Platform */
            platform: string;
            /** Authenticated */
            authenticated: boolean;
            /** User */
            user?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ProgressHeadlinePayload */
        ProgressHeadlinePayload: {
            /** Jobid */
            jobId: string;
            /** Headline */
            headline: string;
            /** Headlinepast */
            headlinePast: string;
            /** Summary */
            summary: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Replacescount
             * @default 0
             */
            replacesCount: number;
        };
        /** RegisterRepoRequest */
        RegisterRepoRequest: {
            /** Source */
            source: string;
            /** Clone To */
            clone_to?: string | null;
        };
        /** RegisterRepoResponse */
        RegisterRepoResponse: {
            /** Path */
            path: string;
            /** Source */
            source: string;
            /** Cloned */
            cloned: boolean;
        };
        /** RepoDetailResponse */
        RepoDetailResponse: {
            /** Path */
            path: string;
            /** Originurl */
            originUrl?: string | null;
            /** Basebranch */
            baseBranch?: string | null;
            /** Currentbranch */
            currentBranch?: string | null;
            /**
             * Activejobcount
             * @default 0
             */
            activeJobCount: number;
            /** Platform */
            platform?: string | null;
        };
        /** RepoListResponse */
        RepoListResponse: {
            /** Items */
            items: string[];
        };
        /** ResolveApprovalRequest */
        ResolveApprovalRequest: {
            resolution: components["schemas"]["ApprovalResolution"];
        };
        /** ResolveJobRequest */
        ResolveJobRequest: {
            /** Action */
            action: string;
        };
        /** ResolveJobResponse */
        ResolveJobResponse: {
            /** Resolution */
            resolution: string;
            /** Prurl */
            prUrl?: string | null;
            /** Conflictfiles */
            conflictFiles?: string[] | null;
        };
        /** ResumeJobRequest */
        ResumeJobRequest: {
            /** Instruction */
            instruction: string;
        };
        /** SDKInfoResponse */
        SDKInfoResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Status */
            status: string;
        };
        /** SDKListResponse */
        SDKListResponse: {
            /** Default */
            default: string;
            /** Sdks */
            sdks: components["schemas"]["SDKInfoResponse"][];
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            /** Seq */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Id */
            id: string;
            /** Shell */
            shell: string;
            /** Cwd */
            cwd: string;
            /** Jobid */
            jobId?: string | null;
            /** Pid */
            pid: number;
            /** Clients */
            clients: number;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Maxconcurrentjobs */
            maxConcurrentJobs: number;
            /** Permissionmode */
            permissionMode: string;
            /** Autopush */
            autoPush: boolean;
            /** Cleanupworktree */
            cleanupWorktree: boolean;
            /** Deletebranchaftermerge */
            deleteBranchAfterMerge: boolean;
            /** Artifactretentiondays */
            artifactRetentionDays: number;
            /** Maxartifactsizemb */
            maxArtifactSizeMb: number;
            /** Autoarchivedays */
            autoArchiveDays: number;
            /** Verify */
            verify: boolean;
            /** Selfreview */
            selfReview: boolean;
            /** Maxturns */
            maxTurns: number;
            /** Verifyprompt */
            verifyPrompt: string;
            /** Selfreviewprompt */
            selfReviewPrompt: string;
        };
        /** TranscribeResponse */
        TranscribeResponse: {
            /** Text */
            text: string;
        };
        /** TranscriptPayload */
        TranscriptPayload: {
            /** Jobid */
            jobId: string;
            /** Seq */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            role: components["schemas"]["TranscriptRole"];
            /** Content */
            content: string;
            /** Title */
            title?: string | null;
            /** Turnid */
            turnId?: string | null;
            /** Toolname */
            toolName?: string | null;
            /** Toolargs */
            toolArgs?: string | null;
            /** Toolresult */
            toolResult?: string | null;
            /** Toolsuccess */
            toolSuccess?: boolean | null;
            /** Toolintent */
            toolIntent?: string | null;
            /** Tooltitle */
            toolTitle?: string | null;
            /** Tooldisplay */
            toolDisplay?: string | null;
            /** Toolgroupsummary */
            toolGroupSummary?: string | null;
        };
        /**
         * TranscriptRole
         * @enum {string}
         */
        TranscriptRole: "agent" | "operator" | "tool_call" | "reasoning" | "divider";
        /**
         * UpdateSettingsRequest
         * @description Structured settings update — only include fields to change.
         */
        UpdateSettingsRequest: {
            /** Maxconcurrentjobs */
            maxConcurrentJobs?: number | null;
            permissionMode?: components["schemas"]["PermissionMode"] | null;
            /** Autopush */
            autoPush?: boolean | null;
            /** Cleanupworktree */
            cleanupWorktree?: boolean | null;
            /** Deletebranchaftermerge */
            deleteBranchAfterMerge?: boolean | null;
            /** Artifactretentiondays */
            artifactRetentionDays?: number | null;
            /** Maxartifactsizemb */
            maxArtifactSizeMb?: number | null;
            /** Autoarchivedays */
            autoArchiveDays?: number | null;
            /** Verify */
            verify?: boolean | null;
            /** Selfreview */
            selfReview?: boolean | null;
            /** Maxturns */
            maxTurns?: number | null;
            /** Verifyprompt */
            verifyPrompt?: string | null;
            /** Selfreviewprompt */
            selfReviewPrompt?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceEntry */
        WorkspaceEntry: {
            /** Path */
            path: string;
            type: components["schemas"]["WorkspaceEntryType"];
            /** Sizebytes */
            sizeBytes?: number | null;
        };
        /**
         * WorkspaceEntryType
         * @enum {string}
         */
        WorkspaceEntryType: "file" | "directory";
        /** WorkspaceListResponse */
        WorkspaceListResponse: {
            /** Items */
            items: components["schemas"]["WorkspaceEntry"][];
            /** Cursor */
            cursor: string | null;
            /** Hasmore */
            hasMore: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                state?: string | null;
                limit?: number;
                cursor?: string | null;
                archived?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_job_api_jobs__job_id__rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_job_api_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_job_api_jobs__job_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_api_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_job_logs_api_jobs__job_id__logs_get: {
        parameters: {
            query?: {
                level?: string;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogLinePayload"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_diff_api_jobs__job_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffFileModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_transcript_api_jobs__job_id__transcript_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPayload"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_timeline_api_jobs__job_id__timeline_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressHeadlinePayload"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_telemetry_api_jobs__job_id__telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_job_api_jobs__job_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_job_api_jobs__job_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_job_api_jobs__job_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                "Last-Event-ID"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_api_jobs__job_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_approval_api_approvals__approval_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trust_job_api_jobs__job_id__approvals_trust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_jobs__job_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspace_api_jobs__job_id__workspace_get: {
        parameters: {
            query?: {
                path?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_file_api_jobs__job_id__workspace_file_get: {
        parameters: {
            query: {
                /** @description Relative path within the worktree */
                path: string;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_api_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_transcribe_api_voice_transcribe_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repos_api_settings_repos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoListResponse"];
                };
            };
        };
    };
    register_repo_endpoint_api_settings_repos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterRepoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_detail_api_settings_repos__repo_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_repo_endpoint_api_settings_repos__repo_path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_worktrees_api_settings_cleanup_worktrees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    browse_directories_api_settings_browse_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_status_api_platforms_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStatusListResponse"];
                };
            };
        };
    };
    list_sdks_api_sdks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SDKListResponse"];
                };
            };
        };
    };
    list_sessions_api_terminal_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    create_session_api_terminal_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_terminal_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ai_api_terminal_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
